id: 6417fb41383a4d66940e751738a734bc
initial_creation_type: ocr
source_metadata:
  volumes:
    070bb9b519204e6cb4129ec0e8180786:
      base_file: v064.txt
      image_group_id: I1PD95910
      title: འཕགས་པ་དགོངས་པ་ངེས་པར་འགྲེལ་པའི་རྣམ་པར་བཤད་པ།
      total_pages: 1498
      volume_number: 65
